#!/usr/bin/env ruby

require 'rb-inotify'
require 'yaml'

config_file = File.join(ENV['HOME'], '.lessd', 'lessd.yml')

if !File.exist?(config_file)
  Dir.mkdir(File.join(ENV['HOME'], '.lessd'))
  File.open(config_file, 'a') do |f| 
    f.puts 'exclude:' 
    f.puts '  - \.inc\.less$'
    f.puts '  - safe_save_\d+'
    f.puts 'paths:'
    f.puts '  - /var/www/css'
  end
end

$config = YAML::load(File.open(config_file))

# Convert the excludes to regexes once
$config['exclude'].map! do |exclusion|
  exclusion = Regexp.new(exclusion)
end

# Test if the path matches any excluded regexes
def excluded?(less)
  $config['exclude'].each do |exclusion| 
    if exclusion.match(less)
      return true
    end
  end
  return false
end

notifier = INotify::Notifier.new

$config['paths'].each do |path|
  begin
    notifier.watch(path, :create, :modify, :recursive) do |event|
      if /\.less$/.match(event.name)
        Dir.chdir(event.notifier.watchers[event.watcher_id].path)
        less = File.join(event.notifier.watchers[event.watcher_id].path, event.name)
        if !excluded? less
          css = less.gsub(/\.less$/, '.css')
          puts "lessc #{less} > #{css}"
          system "lessc #{less} > #{css}"
        end
      end
    end
  rescue
    warn $!
  end
end

notifier.run
