#!/usr/bin/env ruby

require 'daemons'

Daemons.run(File.join(File.dirname(__FILE__), 'lessd'), { 
  :dir_mode   => :normal, 
  :dir        => File.join(ENV['HOME'], '.lessd'),
  :monitor    => true,
  :log_output => true
})
